# Generated by Django 5.0.4 on 2024-05-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyer',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dom.membre'),
            preserve_default=False,
        ),
    ]
