# Generated by Django 5.0.4 on 2024-05-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0004_foyer_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stain',
            new_name='Tache',
        ),
    ]
