# Generated by Django 5.0.4 on 2024-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0005_rename_stain_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='prenom',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
