# Generated by Django 5.0.4 on 2024-05-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0006_membre_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='foyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dom.foyer'),
            preserve_default=False,
        ),
    ]
